### ISSUE TITLE
Using ubxlib directly with ublox gps receivers

### ISSUE THREAD

**Issue by foxittt** [renestraub/ubxlib#49]
Is it possible to use ubxlib directly with ublox gps receivers?

**Comment by renestraub** [comment]
Yes, that's one of the use-cases. Please see examples/show_version_tty.py.

Technically speaking there are two modem server/backends:

- server_tty: direct access to modem via a TTY (you need to know bitrate)
- server.py: uses gpsd control interface

Just import and setup the one you require. In examples/show_port_config.py both options are implemented, one active/one commented out.
